name: development

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_DEVELOPMENT}}
          port: ${{secrets.PORT_DEVELOPMENT}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: ${{secrets.SCRIPT_DEVELOPMENT}}
